const products = [
    {
      id: 1,
      title: 'MEDIHEAL BAOBAB SOOTHING MOISTURE FOAM CLEANSER 120ML',
      category: 'nega lica',
      price: 2076.00,
      img: './images/nl-1.jpg',
      desc: `Ova nežna pena za čišćenje održava savršenu ravnotežu od 5.5 pH, ne uklanjajući prirodno ulje i vlažnost kože. `,
      isFavourite: 0,
    },
    {
      id: 2,
      title: 'MEDIHEAL TEA TREE BIOME BLEMISH CICA GEL CLEANSER 200ML',
      category: 'nega lica',
      price: 1816.00 ,
      img: './images/nl-2.jpg',
      desc: `Hidratantni čistač koji vašu kožu štiti od gubitka vlage. PHA komponenta pomaže u uklanjanju keratina čime se olakšava apsorbcija preparata za negu koji se koriste nakon čišćenja. `,
      isFavourite: 0,
    },
    {
      id: 3,
      title: 'MIZON SNAIL REPAIR INTENSIVE GOLD EYE GEL PATCH',
      category: 'nega lica',
      price: 2450.00,
      img: './images/nl-3.jpg',
      desc: `Hidrogel maska za predeo ispod očiju, na bazi puževe sluzi, obezbeđuje hidrataciju i negu suvoj i umornoj koži.`,
      isFavourite: 0,
    },
    {
      id: 4,
      title: 'AF ŠAMPON BREZA I ARNIKA 1000ML',
      category: 'nega kose',
      price: 350.00,
      img: './images/nk-1.jpg',
      desc: `Uklanja masnoću s kose i vlasišta, uklanja perut i jača strukturu kose. Za temeljnu negu masne kose i vlasište s peruti. `,
      isFavourite: 0,
    },
    {
      id: 5,
      title: '1922 BY J.M BY KEUNE ESSENTIAL ŠAMPON 250ML',
      category: 'nega kose',
      price: 1150.00,
      img: './images/nk-2.jpg',
      desc: `Kada kažemo esencijalni, zaista tako i mislimo. Ovaj šampon je toliko blag da ga možete koristiti svaki dan, za čišćenje i hidrataciju kose, brade i tela.`,
      isFavourite: 0,
    },
    {
      id: 6,
      title: 'AROUND ME SCALP SCALING TRETMAN ZA DUBINSKI OPORAVAK KOŽE GLAVE I KOSE',
      category: 'nega kose',
      price: 1960.00,
      img: './images/nk-3.jpg',
      desc: `Around me Scalp Balancing tretman obezbeđuje momentalnu negu,dubinsku hidrataciju, odgovarajući Ph balans i reguliše proizvodnju sebuma. `,
      isFavourite: 0,
    },
    {
      id: 7,
      title: 'BO BADEMOVA KREMA 200ML',
      category: 'nega tela',
      price: 250.00,
      img: './images/nt-1.jpg',
      desc: `Bones krema za ruke sa bademovim uljem i ekstraktom nevena. `,
      isFavourite: 0,
    },
    {
      id: 8,
      title: 'AF SET BOUQUET OF FLOWERS',
      category: 'nega tela',
      price: 940.00,
      img: './images/nt-2.jpg',
      desc: `Poklon paket sadrži:
      Kremni gel za tuširanje BOUQUET OF FLOWERS i Negujuće mleko za telo BOUQUET OF FLOWERS  `,
      isFavourite: 0,
    },
    {
      id: 9,
      title: 'EQ ALOE VERA DERMO GEL 150ML',
      category: 'nega tela',
      price: 1360.00,
      img: './images/nt-3.jpg',
      desc: `Equilibra® Aloe Dermo-Gel, dobijen presovanjem listova biljke Aloe Vera, u svom sastavu ima čak 98% ovog delotvornog sastojka.`,
      isFavourite: 0,
    },
  ];
  export default products;